### ISSUE TITLE
Error: Cannot find module '../lib/src/Cluster'

### ISSUE THREAD

**Issue by sgluss** [connor4312/js-fuzz#2]
very cool project!

I am trying to get the basic example to run, so far no luck

1. pulled the repo into `project/lib`
2. ran npm install in `project/lib`
3. created sample test file `project/main.js`
4. attempted to run command `node lib/bin/js-fuzz main.js`
5. received error and stacktrace:

module.js:487
    throw err;
    ^

Error: Cannot find module '../lib/src/Cluster'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sam/projects/fuzzTest/lib/bin/js-fuzz:7:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by adrianheine** [comment]
You have to run `npm run build:dist`.

**Comment by sgluss** [comment]
ok, a step in the right direction!

from `project/lib`:
executed `npm run build:dist`

from `project/`
executed `node lib/bin/js-fuzz main.js`

I see the test UI pop up, but it is blank:
![screen shot 2017-11-03 at 4 18 10 pm](https://user-images.githubusercontent.com/12822580/32399381-a7b1207a-c0b2-11e7-8160-fe816f8be73b.png)

Then this error, and trace:
> TypeError: content.getContent is not a function
>     at Log.List.add.List.addItem.List.appendItem (/Users/sam/projects/fuzzTest/lib/node_modules/blessed/lib/widgets/list.js:297:61)
>     at Log.List.setItems (/Users/sam/projects/fuzzTest/lib/node_modules/blessed/lib/widgets/list.js:384:12)
>     at Log.log (/Users/sam/projects/fuzzTest/lib/node_modules/blessed-contrib/lib/widget/log.js:26:8)
>     at Stats.<anonymous> (/Users/sam/projects/fuzzTest/lib/lib/src/Stats.js:203:66)
>     at emitOne (events.js:115:13)
>     at Stats.emit (events.js:210:7)
>     at Stats.log (/Users/sam/projects/fuzzTest/lib/lib/src/Stats.js:76:14)
>     at Cluster.<anonymous> (/Users/sam/projects/fuzzTest/lib/lib/src/Cluster.js:149:67)
>     at emitOne (events.js:115:13)
>     at Cluster.emit (events.js:210:7)

**Comment by adrianheine** [comment]
That's probably the same as #1.

**Comment by sgluss** [comment]
That did the trick exactly. Should I cook up a PR to update the readme and example code?

Thank you very much for your help!

**Comment by adrianheine** [comment]
I opened #6, I hope that does the trick.
