### ISSUE TITLE
Why have you stopped working on this project?

### ISSUE THREAD

**Issue by NF997** [connor4312/js-fuzz#8]
@connor4312 May I ask you why you have stopped working on this project?
Since I am planning to write a bachelor thesis about whitebox fuzzing for JS apps, I would be interested, if you just didn't have the time to work on it any longer or if you encountered some serious problems.

**Comment by connor4312** [comment]
Just life. Some people have pinged me on twitter [recently](https://twitter.com/banescusebi/status/1149022925787455496) about this which got it back in my queue. Keep an eye out, I expect to start working on this again this weekend/next week!
